name: GitHub Actions Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
      
jobs:
 build:
    runs-on: ${{ matrix.os }}

    timeout-minutes: 10

    strategy:
      matrix:
        node_version: [14.x, 16.x]
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    steps:
    - name: Print a greeting
      run: |
        echo hello.
